# Generated by Django 3.1.4 on 2020-12-19 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='descripton',
            new_name='description',
        ),
    ]
