# Generated by Django 3.1.4 on 2020-12-15 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='realtor',
            old_name='phono',
            new_name='phone',
        ),
    ]
